CREATE TABLE COUNTRY(
	CODE NVARCHAR(3),
	NAME NVARCHAR(44),
	CONTINENT NVARCHAR(13),
	REGION NVARCHAR(25),
	SURFACEAREA INTEGER,
	INDEPYEAR NVARCHAR(5),
	POPULATION INTEGER,
	LIFEEXPECTANCY NVARCHAR(4),
	GNP INTEGER,
	GNPOLD NVARCHAR(9),
	LOCALNAME NVARCHAR(44),
	GOVERNMENTFORM NVARCHAR(44),
	HEADOFSTATE NVARCHAR(32),
	CAPITAL NVARCHAR(4),
	CODE2 NVARCHAR(2)
);