SELECT CAST(LAT_N AS DECIMAL(10, 4))
FROM (SELECT LAT_N, ROW_NUMBER() OVER (ORDER BY LAT_N DESC) AS RNUM1 FROM STATION) T1
WHERE RNUM1 = (SELECT CASE 
WHEN MAX(RNUM) % 2 = 0 THEN MAX(RNUM) / 2
ELSE MAX(RNUM) /2 + 1
END
FROM (SELECT LAT_N, ROW_NUMBER() OVER (ORDER BY LAT_N DESC) AS RNUM FROM STATION) T);